---
- name: Create tool download directory
  file:
    path: /home/vagrant/downloads
    owner: vagrant
    group: vagrant
    mode: 0775
    state: directory

- name: Download Vault
  get_url: url="https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip" dest="/home/vagrant/downloads/vault_{{vault_version}}_linux_amd64.zip"
  notify: unzip vault

- name: Write vault systemd service file
  copy: src=vault.service dest=/lib/systemd/system/vault.service mode=u=rw,g=r,o= owner=root group=root

- name: Add VAULT_ADDR variable to be sourced on login
  blockinfile:
    path: /home/vagrant/.bash_profile
    block: |
      export VAULT_ADDR="http://127.0.0.1:8200"
      export VAULT_SKIP_VERIFY=1

- name: Write vault config file
  template: src=vault.conf.j2 dest=/etc/vault.conf mode=u=rw,g=r,o=

- meta: flush_handlers

- name: Enable and start vault service
  systemd:
    name: vault.service
    state: started
    enabled: True